import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://qxigevxcqkdsapxosvhh.supabase.co';
const SUPABASE_KEY='sb_publishable_G_lto6J9yokrmYH8ib7trQ_KP1Lajbn';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});

const state={profile:null,page:'dashboard',jobsTab:'setup',tasksTab:'mine',attendanceTab:'live',projects:[],tasks:[],profiles:[],members:[],assignees:[],timeEntries:[],phaseBudgets:[],changeOrders:[],devices:[],leaveRequests:[],shifts:[],specialDays:[],screenshots:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number(v)||0; const fmt=v=>num(v).toFixed(2); const fmtTime=h=>`${Math.floor(num(h))}:${String(Math.round((num(h)%1)*60)).padStart(2,'0')}`;
const isoDay=()=>new Date().toISOString().slice(0,10);
function setSync(t){const e=$('#syncStatus');if(e)e.textContent=t}
function roleIsAdmin(){return state.profile?.role==='Admin'} function roleIsManager(){return ['Admin','Manager'].includes(state.profile?.role)}
function pById(id){return state.projects.find(x=>x.id===id)} function tById(id){return state.tasks.find(x=>x.id===id)} function prof(id){return state.profiles.find(x=>x.id===id)} function nameOf(id){const p=prof(id);return p?.display_name||p?.employee_id||p?.email||'—'}
function projectMembers(pid){return state.members.filter(x=>x.project_id===pid)} function projectLead(pid){return projectMembers(pid).find(x=>String(x.role_in_project).toLowerCase()==='lead')}
function isLead(pid){return projectLead(pid)?.user_id===state.profile?.id} function canManageProject(pid){return roleIsAdmin()||roleIsManager()||isLead(pid)}
async function safe(table,query='*'){try{const {data,error}=await supabase.from(table).select(query);if(error)throw error;return data||[]}catch(e){console.warn(table,e);return[]}}
async function loadAll(){setSync('Loading...');const [projects,tasks,profiles,members,assignees,timeEntries,phaseBudgets,changeOrders,devices,leaveRequests,shifts,specialDays,screenshots]=await Promise.all([
 safe('projects'),safe('tasks'),safe('profiles'),safe('project_members'),safe('task_assignees'),safe('time_entries'),safe('project_phase_budgets'),safe('change_orders'),safe('devices'),safe('leave_requests'),safe('work_shift_settings'),safe('special_work_days'),safe('screenshots')]);
 Object.assign(state,{projects:projects.filter(x=>x.active!==false),tasks:tasks.filter(x=>x.active!==false),profiles,members,assignees,timeEntries,phaseBudgets,changeOrders,devices,leaveRequests,shifts,specialDays,screenshots});setSync('Supabase ✓');render();}
function taskHours(tid){const now=Date.now();return state.timeEntries.filter(x=>x.task_id===tid).reduce((s,x)=>{if(num(x.duration_seconds)>0)return s+num(x.duration_seconds)/3600;if(x.started_at&&!x.ended_at)return s+(now-new Date(x.started_at).getTime())/3600000;if(x.started_at&&x.ended_at)return s+(new Date(x.ended_at)-new Date(x.started_at))/3600000;return s},0)}
function projectHours(pid){return state.tasks.filter(t=>t.project_id===pid).reduce((s,t)=>s+taskHours(t.id),0)}
function originalHours(pid){return state.phaseBudgets.filter(x=>x.project_id===pid).reduce((s,x)=>s+num(x.estimated_hours),0)}
function approvedHours(pid){return state.changeOrders.filter(x=>x.project_id===pid&&String(x.status).toLowerCase()==='approved').reduce((s,x)=>s+num(x.approved_hours??x.requested_hours),0)}
function openCO(pid){return state.changeOrders.filter(x=>x.project_id===pid&&!['approved','rejected'].includes(String(x.status).toLowerCase())).length}
function statusClass(s){s=String(s||'').toLowerCase();return s.includes('approved')||s.includes('track')||s.includes('done')||s==='tracking'?'good':s.includes('pending')||s.includes('progress')||s.includes('risk')?'warn':s.includes('reject')||s.includes('over')||s.includes('offline')?'bad':''}
function modal(title,html,onSave,saveText='Save'){ $('#modal').innerHTML=`<h3>${esc(title)}</h3>${html}<div class="modal-actions"><button id="mCancel">Cancel</button>${onSave?`<button id="mSave" class="primary">${esc(saveText)}</button>`:''}</div>`;$('#modalBackdrop').classList.remove('hidden');$('#mCancel').onclick=closeModal;if(onSave)$('#mSave').onclick=onSave} function closeModal(){$('#modalBackdrop').classList.add('hidden')}

async function getProfile(user){const {data}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();return data||{id:user.id,email:user.email,display_name:user.email,role:'Employee'}}
async function showMain(user){state.profile=await getProfile(user);$('#loginView').classList.add('hidden');$('#mainView').classList.remove('hidden');$('#monitorNav').classList.toggle('hidden',!roleIsManager());$('#employeesNav').classList.toggle('hidden',!roleIsAdmin());$('#userSummary').innerHTML=`<b>${esc(state.profile.display_name||state.profile.email)}</b><br>${esc(state.profile.employee_id||'')} · ${esc(state.profile.role||'Employee')}`;await loadAll()}
$('#loginBtn').onclick=async()=>{const {data,error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});$('#loginMsg').textContent=error?.message||'';if(data?.user)showMain(data.user)};
$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};$('#reloadBtn').onclick=loadAll;
$$('.nav-btn[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;$$('.nav-btn[data-page]').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(p=>p.classList.add('hidden'));$(`#page-${state.page}`).classList.remove('hidden');render()});

function render(){const titles={dashboard:['Dashboard','Project portfolio overview'],jobs:['Jobs','Project setup, list, change orders and project time'],tasks:['Tasks','My work and task management'],production:['Production','Task production progress'],screenshots:['Screenshots','Cloud screenshots from Tracking desktop agent'],attendance:['Attendance','Live team, leave, schedules and leave balances'],monitor:['Team Monitor','Employee screenshots by date'],employees:['Employees','Employee accounts, roles and leave balances'],settings:['Settings','Web portal preferences'],about:['About','DDG Tracking Web']};const t=titles[state.page]||['Tracking',''];$('#pageTitle').textContent=t[0];$('#pageSubtitle').textContent=t[1];({dashboard:renderDashboard,jobs:renderJobs,tasks:renderTasks,production:renderProduction,screenshots:renderScreenshots,attendance:renderAttendance,monitor:renderMonitor,employees:renderEmployees,settings:renderSettings,about:renderAbout}[state.page]||(()=>{}))()}

function renderDashboard(){const active=state.projects.length,atRisk=state.projects.filter(p=>p.status==='At Risk').length,over=state.projects.filter(p=>projectHours(p.id)>originalHours(p.id)+approvedHours(p.id)&&originalHours(p.id)+approvedHours(p.id)>0).length,hold=state.projects.filter(p=>p.status==='On Hold').length,pending=state.changeOrders.filter(c=>String(c.status).toLowerCase()==='pending').length,unapproved=state.changeOrders.filter(c=>String(c.status).toLowerCase()==='pending').reduce((s,c)=>s+num(c.requested_hours),0);const attention=state.projects.filter(p=>['At Risk','Over Hours','On Hold'].includes(p.status)||openCO(p.id));const coRows=[...state.changeOrders].sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0)).slice(0,12);
 $('#page-dashboard').innerHTML=`<div class="grid kpis">${[['Active Projects',active],['Projects At Risk',atRisk],['Projects Over Hours',over],['Projects On Hold',hold],['Pending Change Orders',pending],['Unapproved Hours',fmt(unapproved)]].map(x=>`<div class="kpi"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('')}</div>
 <div class="card"><div class="section-title">Project Portfolio (${state.projects.length} Projects)</div>${projectPortfolioTable()}</div>
 <div class="grid three-col" style="margin-top:12px"><div class="card"><div class="section-title">Projects Requiring Attention</div><div class="table-wrap"><table class="table"><thead><tr><th>Project</th><th>Main Issue</th><th>Progress</th><th>Status</th></tr></thead><tbody>${attention.map(p=>`<tr><td>${esc(p.name)}</td><td>${openCO(p.id)?'Pending Change Order':esc(p.status)}</td><td>${num(p.overall_progress).toFixed(0)}%</td><td>${esc(p.status||'Not Started')}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="card"><div class="section-title">Change Orders Requiring Action</div><div class="table-wrap"><table class="table"><thead><tr><th>CO</th><th>Project</th><th>Description</th><th>Requested</th><th>Status</th></tr></thead><tbody>${coRows.map(c=>`<tr><td>${esc(c.co_no||'—')}</td><td>${esc(pById(c.project_id)?.name||'—')}</td><td>${esc(c.description||'')}</td><td>${fmt(c.requested_hours)}</td><td><span class="status ${statusClass(c.status)}">${esc(c.status||'Pending')}</span></td></tr>`).join('')}</tbody></table></div></div>
 <div class="card"><div class="section-title">Estimated vs Used Hours (Top 5)</div>${state.projects.slice().sort((a,b)=>(originalHours(b.id)+approvedHours(b.id))-(originalHours(a.id)+approvedHours(a.id))).slice(0,5).map(p=>{const est=originalHours(p.id)+approvedHours(p.id),used=projectHours(p.id),pct=est?Math.min(100,used/est*100):0;return`<div style="margin:13px 0"><b>${esc(p.name)}</b><div class="muted small">${fmt(used)} / ${fmt(est)} h</div><div class="progressbar" style="width:100%;margin-top:4px"><i style="width:${pct}%"></i></div></div>`}).join('')}</div></div>`}
function projectPortfolioTable(){return `<div class="table-wrap"><table class="table"><thead><tr><th>Project</th><th>Customer</th><th>Project Manager</th><th>Current Phase</th><th>Due</th><th>Original Hours</th><th>Original Used</th><th>Approved CO Hours</th><th>CO Hours Used</th><th>Revised Hours</th><th>Hours Used</th><th>Over Approved</th><th>Remaining Hours</th><th>Overall Progress</th><th>Budget Used %</th><th>Status</th><th>Open COs</th></tr></thead><tbody>${state.projects.map(p=>{const o=originalHours(p.id),a=approvedHours(p.id),u=projectHours(p.id),r=o+a,rem=Math.max(0,r-u),over=Math.max(0,u-r),pct=r?Math.min(999,u/r*100):0;return`<tr><td>${esc(p.name)}</td><td>${esc(p.customer||'—')}</td><td>${esc(p.project_manager||'—')}</td><td>${esc(p.current_phase||'—')}</td><td>${esc(p.due_date||'—')}</td><td>${fmt(o)}</td><td>${fmt(Math.min(u,o))}</td><td>${fmt(a)}</td><td>${fmt(Math.max(0,u-o))}</td><td>${fmt(r)}</td><td>${fmt(u)}</td><td>${fmt(over)}</td><td>${fmt(rem)}</td><td>${num(p.overall_progress).toFixed(0)}%</td><td>${pct.toFixed(0)}%</td><td><span class="status ${statusClass(p.status)}">${esc(p.status||'Not Started')}</span></td><td>${openCO(p.id)}</td></tr>`}).join('')}</tbody></table></div>`}

function tabs(items,active,handler){return `<div class="tabbar">${items.map(([key,label])=>`<button class="tab-btn ${active===key?'active':''}" data-subtab="${key}">${label}</button>`).join('')}</div>`}
function hookTabs(container,setter){container.querySelectorAll('[data-subtab]').forEach(b=>b.onclick=()=>{setter(b.dataset.subtab);render()})}
function renderJobs(){const el=$('#page-jobs');el.innerHTML=tabs([['setup','Project Setup'],['list','Project List'],['co','Change Orders'],['time','Project Time']],state.jobsTab)+`<div id="jobsBody"></div>`;hookTabs(el,v=>state.jobsTab=v);if(state.jobsTab==='setup')renderProjectSetup();if(state.jobsTab==='list')$('#jobsBody').innerHTML=`<div class="card">${projectPortfolioTable()}</div>`;if(state.jobsTab==='co')renderCO(true);if(state.jobsTab==='time')renderProjectTime()}
function projectOptions(selected=''){return state.projects.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.name)}</option>`).join('')}
function renderProjectSetup(){const body=$('#jobsBody');const pid=state.projects[0]?.id||'';body.innerHTML=`<div class="toolbar"><div class="field grow"><label>Project</label><select id="setupProject">${projectOptions(pid)}</select></div>${roleIsManager()?'<button id="newProject">+ New Project</button><button id="renameProject">Rename</button><button id="deleteProject" class="danger">Delete</button>':''}<button id="teamProject">Manage Team</button><button id="saveSetup" class="primary">Save Project Setup</button></div><div id="setupForm"></div>`;const sel=$('#setupProject');sel.onchange=()=>drawSetupForm(sel.value);drawSetupForm(sel.value);if(roleIsManager()){ $('#newProject').onclick=()=>projectModal();$('#renameProject').onclick=()=>projectModal(pById(sel.value),true);$('#deleteProject').onclick=()=>archiveProject(sel.value)}$('#teamProject').onclick=()=>teamModal(sel.value);$('#saveSetup').onclick=()=>saveProjectSetup(sel.value)}
function uniqueVals(field){return [...new Set(state.projects.map(p=>p[field]).filter(Boolean))].sort()}
function drawSetupForm(pid){const p=pById(pid),box=$('#setupForm');if(!p){box.innerHTML='<div class="notice">No project selected.</div>';return}const ms=projectMembers(pid),lead=projectLead(pid),phases=state.phaseBudgets.filter(x=>x.project_id===pid).sort((a,b)=>num(a.sort_order)-num(b.sort_order));box.innerHTML=`
 <div class="card"><div class="section-title">Project Information</div><div class="form-grid">
 <div class="field"><label>Project / Job Number</label><input id="pjJob" value="${esc(p.job_number||p.package_no||'')}"></div>
 <div class="field"><label>Customer</label><input id="pjCustomer" list="customerList" value="${esc(p.customer||'')}"><datalist id="customerList">${uniqueVals('customer').map(v=>`<option value="${esc(v)}">`).join('')}</datalist></div>
 <div class="field"><label>Project Manager</label><input id="pjPM" list="pmList" value="${esc(p.project_manager||'')}"><datalist id="pmList">${[...new Set([...uniqueVals('project_manager'),...state.profiles.map(x=>x.display_name).filter(Boolean)])].map(v=>`<option value="${esc(v)}">`).join('')}</datalist></div>
 <div class="field"><label>Office</label><input id="pjOffice" list="officeList" value="${esc(p.office||'')}"><datalist id="officeList">${uniqueVals('office').map(v=>`<option value="${esc(v)}">`).join('')}</datalist></div>
 <div class="field"><label>Current Phase</label><select id="pjPhase"><option value="">—</option>${phases.map(x=>`<option ${x.phase===p.current_phase?'selected':''}>${esc(x.phase)}</option>`).join('')}</select></div>
 <div class="field"><label>Current Status</label><select id="pjStatus">${['Not Started','On Track','At Risk','Over Hours','On Hold','Completed'].map(v=>`<option ${v===p.status?'selected':''}>${v}</option>`).join('')}</select></div>
 <div class="field"><label>Start Date</label><input id="pjStart" type="date" value="${esc(p.start_date||'')}"></div><div class="field"><label>Due Date</label><input id="pjDue" type="date" value="${esc(p.due_date||'')}"></div>
 <div class="field"><label>Priority</label><select id="pjPriority">${['','Low','Normal','High','Urgent'].map(v=>`<option ${v===p.priority?'selected':''}>${v||'—'}</option>`).join('')}</select></div>
 <div class="field"><label>Project Lead</label><select id="pjLead" ${roleIsAdmin()?'':'disabled'}><option value="">No Project Lead</option>${ms.map(m=>`<option value="${m.user_id}" ${lead?.user_id===m.user_id?'selected':''}>${esc(nameOf(m.user_id))}</option>`).join('')}</select></div>
 <div class="field span2"><label>Assigned Team Members</label><input readonly value="${esc(ms.map(m=>nameOf(m.user_id)).join(' · '))}"></div></div></div>
 <div class="card" style="margin-top:12px"><div class="section-title">Hours & Progress</div><div class="metric-grid">${[['Original Hours',originalHours(pid)],['Original Hours Used',Math.min(projectHours(pid),originalHours(pid))],['Approved Change Order Hours',approvedHours(pid)],['CO Hours Used',Math.max(0,projectHours(pid)-originalHours(pid))],['Remaining CO Hours',Math.max(0,approvedHours(pid)-Math.max(0,projectHours(pid)-originalHours(pid)))],['Over Approved Hours',Math.max(0,projectHours(pid)-originalHours(pid)-approvedHours(pid))],['Revised Hours',originalHours(pid)+approvedHours(pid)],['Hours Used',projectHours(pid)],['Remaining Hours',Math.max(0,originalHours(pid)+approvedHours(pid)-projectHours(pid))]].map(([l,v])=>`<div class="metric"><div class="label">${l} [AUTO]</div><div class="value">${fmt(v)}</div></div>`).join('')}<div class="field"><label>Overall Progress %</label><input id="pjProgress" type="number" min="0" max="100" value="${num(p.overall_progress)}"></div></div></div>
 <div class="card" style="margin-top:12px"><div class="toolbar"><div class="section-title grow">Progress by Phase</div>${canManageProject(pid)?'<button id="addPhase">+ Add Phase</button>':''}</div><div class="table-wrap"><table class="table"><thead><tr><th>Phase</th><th>Estimated Hours</th><th>Hours Used</th><th>Remaining Hours</th><th>Progress</th><th>Status</th><th>Action</th></tr></thead><tbody>${phases.map(ph=>{const used=state.tasks.filter(t=>t.project_id===pid&&t.phase===ph.phase).reduce((s,t)=>s+taskHours(t.id),0),est=num(ph.estimated_hours),pct=est?Math.min(100,used/est*100):0;return`<tr><td>${esc(ph.phase)}</td><td>${fmt(est)}</td><td>${fmt(used)}</td><td>${fmt(Math.max(0,est-used))}</td><td>${pct.toFixed(0)}%</td><td>${used<=0?'Not Started':used<est?'On Track':'Completed'}</td><td>${canManageProject(pid)?`<button data-edit-phase="${ph.id}">Edit</button> <button class="danger" data-del-phase="${ph.id}">Remove</button>`:''}</td></tr>`}).join('')}</tbody></table></div></div>`;
 if($('#addPhase'))$('#addPhase').onclick=()=>phaseModal(pid);$$('[data-edit-phase]').forEach(b=>b.onclick=()=>phaseModal(pid,phases.find(x=>x.id===b.dataset.editPhase)));$$('[data-del-phase]').forEach(b=>b.onclick=()=>deletePhase(b.dataset.delPhase,pid))}
async function saveProjectSetup(pid){const row={job_number:$('#pjJob').value.trim(),customer:$('#pjCustomer').value.trim(),project_manager:$('#pjPM').value.trim(),office:$('#pjOffice').value.trim(),current_phase:$('#pjPhase').value||null,status:$('#pjStatus').value,start_date:$('#pjStart').value||null,due_date:$('#pjDue').value||null,priority:$('#pjPriority').value||null,overall_progress:num($('#pjProgress').value)};const {error}=await supabase.from('projects').update(row).eq('id',pid);if(error)return alert(error.message);if(roleIsAdmin())await setProjectLead(pid,$('#pjLead').value);await loadAll()}
async function setProjectLead(pid,uid){const ms=projectMembers(pid);for(const m of ms.filter(x=>String(x.role_in_project).toLowerCase()==='lead'&&x.user_id!==uid))await supabase.from('project_members').update({role_in_project:'member'}).eq('project_id',pid).eq('user_id',m.user_id);if(uid)await supabase.from('project_members').update({role_in_project:'lead'}).eq('project_id',pid).eq('user_id',uid)}
function phaseModal(pid,ph=null){modal(ph?'Edit Phase':'Add Phase',`<div class="form-grid"><div class="field"><label>Phase</label><input id="phName" value="${esc(ph?.phase||'')}"></div><div class="field"><label>Estimated Hours</label><input id="phHours" type="number" min="0" step="0.25" value="${num(ph?.estimated_hours)}"></div></div>`,async()=>{const row={project_id:pid,phase:$('#phName').value.trim(),estimated_hours:num($('#phHours').value),sort_order:ph?.sort_order??state.phaseBudgets.filter(x=>x.project_id===pid).length+1};if(!row.phase)return alert('Phase is required.');let r=ph?await supabase.from('project_phase_budgets').update(row).eq('id',ph.id):await supabase.from('project_phase_budgets').insert(row);if(r.error)return alert(r.error.message);closeModal();await loadAll()})}
async function deletePhase(id,pid){const ph=state.phaseBudgets.find(x=>x.id===id);if(state.tasks.some(t=>t.project_id===pid&&t.phase===ph?.phase))return alert('Move Tasks to another Phase first.');if(!confirm('Remove this Phase?'))return;const {error}=await supabase.from('project_phase_budgets').delete().eq('id',id);if(error)alert(error.message);else loadAll()}
function projectModal(p=null,renameOnly=false){modal(p?'Edit Project':'New Project',`<div class="form-grid"><div class="field"><label>Project Name</label><input id="mName" value="${esc(p?.name||'')}"></div>${renameOnly?'':`<div class="field"><label>Customer</label><input id="mCustomer" value="${esc(p?.customer||'')}"></div><div class="field"><label>Status</label><select id="mStatus">${['Not Started','On Track','At Risk','Over Hours','On Hold','Completed'].map(x=>`<option ${p?.status===x?'selected':''}>${x}</option>`).join('')}</select></div>`}</div>`,async()=>{const row={name:$('#mName').value.trim()};if(!renameOnly)Object.assign(row,{customer:$('#mCustomer').value.trim(),status:$('#mStatus').value,active:true});const r=p?await supabase.from('projects').update(row).eq('id',p.id):await supabase.from('projects').insert(row);if(r.error)return alert(r.error.message);closeModal();await loadAll()})}
async function archiveProject(id){if(!confirm('Delete/archive this Project? Historical time stays in Supabase.'))return;const {error}=await supabase.from('projects').update({active:false}).eq('id',id);if(error)alert(error.message);else loadAll()}
function teamModal(pid){const selected=projectMembers(pid).map(m=>m.user_id);modal('Manage Project Team',`<div class="check-list">${state.profiles.filter(p=>p.active!==false).map(p=>`<label><input class="teamCheck" type="checkbox" value="${p.id}" ${selected.includes(p.id)?'checked':''}> ${esc(p.display_name||p.email)} ${p.employee_id?'('+esc(p.employee_id)+')':''}</label>`).join('')}</div>`,async()=>{const ids=$$('.teamCheck:checked').map(x=>x.value),old=projectMembers(pid);for(const m of old.filter(x=>!ids.includes(x.user_id)))await supabase.from('project_members').delete().eq('project_id',pid).eq('user_id',m.user_id);for(const uid of ids.filter(x=>!old.some(m=>m.user_id===x))){const r=await supabase.from('project_members').insert({project_id:pid,user_id:uid,role_in_project:'member'});if(r.error)return alert(r.error.message)}closeModal();await loadAll()})}
function renderProjectTime(){const rows=state.projects;$('#jobsBody').innerHTML=`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Project</th><th>Today</th><th>This Week</th><th>All Task Hours</th></tr></thead><tbody>${rows.map(p=>{const entries=state.timeEntries.filter(x=>x.project_id===p.id),today=entryHours(entries.filter(x=>String(x.started_at||'').slice(0,10)===isoDay())),week=entryHours(entries.filter(x=>new Date(x.started_at||0)>new Date(Date.now()-7*86400000)));return`<tr><td>${esc(p.name)}</td><td>${fmtTime(today)}</td><td>${fmtTime(week)}</td><td>${fmt(projectHours(p.id))}</td></tr>`}).join('')}</tbody></table></div></div>`}
function entryHours(rows){const now=Date.now();return rows.reduce((s,x)=>s+(num(x.duration_seconds)>0?num(x.duration_seconds)/3600:x.started_at?((x.ended_at?new Date(x.ended_at).getTime():now)-new Date(x.started_at).getTime())/3600000:0),0)}

function renderTasks(){const el=$('#page-tasks');el.innerHTML=tabs([['mine','My Tasks'],['manage','Task Management']],state.tasksTab)+`<div id="tasksBody"></div>`;hookTabs(el,v=>state.tasksTab=v);if(state.tasksTab==='mine')renderMyTasks();else renderTaskManagement()}
function renderMyTasks(){const mine=state.tasks.filter(t=>state.assignees.some(a=>a.task_id===t.id&&a.user_id===state.profile.id));$('#tasksBody').innerHTML=`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Project</th><th>Task</th><th>Status</th><th>Phase</th><th>Tracked Hours</th><th>Assignees</th></tr></thead><tbody>${mine.map(t=>`<tr><td>${esc(pById(t.project_id)?.name||'—')}</td><td>${esc(t.name)}</td><td>${esc(t.status||'Ready')}</td><td>${esc(t.phase||'—')}</td><td>${fmt(taskHours(t.id))}</td><td>${esc(state.assignees.filter(a=>a.task_id===t.id).map(a=>nameOf(a.user_id)).join(', '))}</td></tr>`).join('')}</tbody></table></div></div>`}
function renderTaskManagement(){const pid=state.projects[0]?.id||'';$('#tasksBody').innerHTML=`<div class="toolbar"><div class="field"><label>Project</label><select id="taskProject">${projectOptions(pid)}</select></div><button id="newTask">+ New Task</button></div><div id="taskGrid"></div>`;const s=$('#taskProject');s.onchange=()=>drawTaskGrid(s.value);$('#newTask').onclick=()=>taskModal(s.value);drawTaskGrid(s.value)}
function drawTaskGrid(pid){const rows=state.tasks.filter(t=>t.project_id===pid);$('#taskGrid').innerHTML=`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Task</th><th>Status</th><th>Phase</th><th>Tracked Hours</th><th>Assignees</th><th>People</th><th>Actions</th></tr></thead><tbody>${rows.map(t=>{const as=state.assignees.filter(a=>a.task_id===t.id).map(a=>nameOf(a.user_id));return`<tr><td>${esc(t.name)}</td><td>${esc(t.status||'Ready')}</td><td>${esc(t.phase||'—')}</td><td>${fmt(taskHours(t.id))} h</td><td>${esc(as.join(', ')||'—')}</td><td>${as.length}</td><td><button data-edit-task="${t.id}">Edit</button> <button class="danger" data-del-task="${t.id}">Delete</button></td></tr>`}).join('')}</tbody></table></div></div>`;$$('[data-edit-task]').forEach(b=>b.onclick=()=>taskModal(pid,tById(b.dataset.editTask)));$$('[data-del-task]').forEach(b=>b.onclick=()=>archiveTask(b.dataset.delTask))}
function taskModal(pid,t=null){const phases=state.phaseBudgets.filter(x=>x.project_id===pid),ms=projectMembers(pid),selected=state.assignees.filter(a=>a.task_id===t?.id).map(a=>a.user_id);modal(t?'Edit Task':'New Task',`<div class="form-grid"><div class="field"><label>Task Name</label><input id="tName" value="${esc(t?.name||'')}"></div><div class="field"><label>Status</label><select id="tStatus">${['Ready','In Progress','On Hold','Done'].map(s=>`<option ${t?.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Phase</label><select id="tPhase"><option value="">No phase</option>${phases.map(ph=>`<option ${t?.phase===ph.phase?'selected':''}>${esc(ph.phase)}</option>`).join('')}</select></div><div class="span3"><b>Assignees</b><div class="check-list">${ms.map(m=>`<label><input type="checkbox" class="asg" value="${m.user_id}" ${selected.includes(m.user_id)?'checked':''}> ${esc(nameOf(m.user_id))}</label>`).join('')||'No Project Members'}</div></div></div>`,async()=>{const row={project_id:pid,name:$('#tName').value.trim(),status:$('#tStatus').value,phase:$('#tPhase').value||null,active:true};let tid=t?.id,r;if(t)r=await supabase.from('tasks').update(row).eq('id',t.id);else{r=await supabase.from('tasks').insert(row).select('id').single();tid=r.data?.id}if(r.error)return alert(r.error.message);await supabase.from('task_assignees').delete().eq('task_id',tid);const ids=$$('.asg:checked').map(x=>x.value);if(ids.length){const a=await supabase.from('task_assignees').insert(ids.map(user_id=>({task_id:tid,user_id})));if(a.error)return alert(a.error.message)}closeModal();await loadAll()})}
async function archiveTask(id){if(!confirm('Delete this Task? Tracking history is kept.'))return;const {error}=await supabase.from('tasks').update({active:false}).eq('id',id);if(error)alert(error.message);else loadAll()}

function renderCO(inJobs=false){const target=inJobs?'#jobsBody':'#page-changeorders',rows=state.changeOrders;$(target).innerHTML=`<div class="toolbar"><div class="field"><label>Project</label><select id="coFilter"><option value="">All Projects</option>${projectOptions()}</select></div><div class="grow"></div><button id="newCO">+ New Change Order</button></div><div class="grid" style="grid-template-columns:repeat(4,1fr);margin-bottom:12px">${[['Requested Hours',rows.reduce((s,x)=>s+num(x.requested_hours),0)],['Approved Hours',rows.filter(x=>String(x.status).toLowerCase()==='approved').reduce((s,x)=>s+num(x.approved_hours??x.requested_hours),0)],['Pending Request',rows.filter(x=>String(x.status).toLowerCase()==='pending').length],['Change Orders',rows.length]].map(([l,v])=>`<div class="kpi"><div class="label">${l}</div><div class="value">${typeof v==='number'?fmt(v):v}</div></div>`).join('')}</div><div id="coGrid"></div>`;$('#newCO').onclick=()=>coModal();$('#coFilter').onchange=()=>drawCOGrid($('#coFilter').value);drawCOGrid('')}
function drawCOGrid(pid){const rows=state.changeOrders.filter(c=>!pid||c.project_id===pid);$('#coGrid').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>CO No.</th><th>Project</th><th>Description</th><th>Requested</th><th>Approved</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.co_no||'—')}</td><td>${esc(pById(c.project_id)?.name||'—')}</td><td>${esc(c.description||'')}</td><td>${fmt(c.requested_hours)}</td><td>${c.approved_hours==null?'—':fmt(c.approved_hours)}</td><td><span class="status ${statusClass(c.status)}">${esc(c.status||'Pending')}</span></td><td>${esc((c.created_at||'').slice(0,10))}</td><td><button data-edit-co="${c.id}">Edit</button> <button class="success" data-approve-co="${c.id}">Approve</button> <button data-reject-co="${c.id}">Reject</button> <button class="danger" data-delete-co="${c.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`;$$('[data-edit-co]').forEach(b=>b.onclick=()=>coModal(state.changeOrders.find(x=>x.id===b.dataset.editCo)));$$('[data-approve-co]').forEach(b=>b.onclick=()=>approveCO(b.dataset.approveCo));$$('[data-reject-co]').forEach(b=>b.onclick=()=>setCOStatus(b.dataset.rejectCo,'Rejected'));$$('[data-delete-co]').forEach(b=>b.onclick=()=>deleteCO(b.dataset.deleteCo))}
function coModal(c=null){modal(c?'Edit Change Order':'New Change Order',`<div class="form-grid"><div class="field"><label>Project</label><select id="coProject">${projectOptions(c?.project_id)}</select></div><div class="field"><label>CO No.</label><input id="coNo" value="${esc(c?.co_no||'')}"></div><div class="field"><label>Requested Hours</label><input id="coReq" type="number" min="0" step="0.25" value="${num(c?.requested_hours)}"></div><div class="field span3"><label>Description</label><textarea id="coDesc" rows="3">${esc(c?.description||'')}</textarea></div></div>`,async()=>{const row={project_id:$('#coProject').value,co_no:$('#coNo').value.trim(),requested_hours:num($('#coReq').value),description:$('#coDesc').value.trim(),status:c?.status||'Pending'};const r=c?await supabase.from('change_orders').update(row).eq('id',c.id):await supabase.from('change_orders').insert(row);if(r.error)return alert(r.error.message);closeModal();await loadAll()})}
function approveCO(id){const c=state.changeOrders.find(x=>x.id===id);modal('Approve Change Order',`<div class="field"><label>Approved Hours</label><input id="apHours" type="number" min="0" step="0.25" value="${num(c?.approved_hours??c?.requested_hours)}"></div>`,async()=>{const h=num($('#apHours').value);const {error}=await supabase.from('change_orders').update({approved_hours:h,status:'Approved'}).eq('id',id);if(error)return alert(error.message);closeModal();await loadAll()},'Approve')}
async function setCOStatus(id,status){const {error}=await supabase.from('change_orders').update({status}).eq('id',id);if(error)alert(error.message);else loadAll()} async function deleteCO(id){if(!confirm('Delete this Change Order?'))return;const {error}=await supabase.from('change_orders').delete().eq('id',id);if(error)alert(error.message);else loadAll()}

function renderProduction(){const rows=state.tasks;$('#page-production').innerHTML=`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Project</th><th>Task</th><th>Trade</th><th>Area</th><th>Level</th><th>Phase</th><th>Sheet Count</th><th>Sheets Done</th><th>Spool Count</th><th>Spools Done</th><th>LF Total</th><th>LF Done</th><th>Progress</th></tr></thead><tbody>${rows.map(t=>{const total=num(t.sheet_count)+num(t.spool_count)+num(t.lf_total),done=num(t.sheets_done)+num(t.spools_done)+num(t.lf_done),pct=total?Math.min(100,done/total*100):0;return`<tr><td>${esc(pById(t.project_id)?.name||'—')}</td><td>${esc(t.name)}</td><td>${esc(t.trade||'—')}</td><td>${esc(t.area||'—')}</td><td>${esc(t.level||'—')}</td><td>${esc(t.phase||'—')}</td><td>${num(t.sheet_count)}</td><td>${num(t.sheets_done)}</td><td>${num(t.spool_count)}</td><td>${num(t.spools_done)}</td><td>${fmt(t.lf_total)}</td><td>${fmt(t.lf_done)}</td><td>${pct.toFixed(0)}%</td></tr>`}).join('')}</tbody></table></div></div>`}

async function signedShot(path){if(!path)return'';for(const bucket of ['screenshots','tracking-screenshots']){const {data,error}=await supabase.storage.from(bucket).createSignedUrl(path,600);if(!error&&data?.signedUrl)return data.signedUrl}return''}
function renderScreenshots(){const mine=state.screenshots.filter(s=>s.user_id===state.profile.id).sort((a,b)=>new Date(b.captured_at||0)-new Date(a.captured_at||0)).slice(0,100);$('#page-screenshots').innerHTML=`<div class="notice">Desktop screenshots are captured by the DDG Tracking desktop agent and synced to Supabase. The browser portal displays synced images.</div><div id="myShots" class="screenshot-grid"></div>`;drawShotCards(mine,$('#myShots'))}
async function drawShotCards(shots,el){el.innerHTML=shots.length?'<div class="muted">Loading previews...</div>':'<div class="muted">No screenshots.</div>';if(!shots.length)return;const cards=[];for(const s of shots){const url=await signedShot(s.storage_path);cards.push(`<article class="shot-card" data-url="${esc(url)}"><div class="shot-thumb">${url?`<img src="${esc(url)}" loading="lazy">`:'Preview unavailable'}</div><div class="shot-meta"><b>${s.captured_at?new Date(s.captured_at).toLocaleString():'—'}</b><span>${esc(pById(s.project_id)?.name||'No project')} · ${esc(tById(s.task_id)?.name||'No task')}</span></div></article>`)}el.innerHTML=cards.join('');el.querySelectorAll('[data-url]').forEach(x=>x.onclick=()=>x.dataset.url&&window.open(x.dataset.url,'_blank'))}

function renderAttendance(){const el=$('#page-attendance');el.innerHTML=tabs([['live','Live Team'],['leave','Leave Requests'],['schedule','Work Schedule & Holidays'],['balance','Leave Balances']],state.attendanceTab)+`<div id="attendanceBody"></div>`;hookTabs(el,v=>state.attendanceTab=v);({live:drawLiveTeam,leave:drawLeave,schedule:drawSchedule,balance:drawBalances}[state.attendanceTab]||drawLiveTeam)()}
function drawLiveTeam(){const now=Date.now(),today=new Date();const approved=state.leaveRequests.filter(l=>String(l.status).toLowerCase()==='approved'&&new Date(l.start_date)<=today&&new Date(l.end_date)>=today);$('#attendanceBody').innerHTML=`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Employee ID</th><th>Role</th><th>Status</th><th>Project</th><th>Task</th><th>Device</th><th>Last Seen</th></tr></thead><tbody>${state.profiles.filter(p=>p.active!==false).map(p=>{const d=state.devices.filter(x=>x.user_id===p.id).sort((a,b)=>new Date(b.last_seen||0)-new Date(a.last_seen||0))[0],onLeave=approved.some(l=>l.user_id===p.id),recent=d&&now-new Date(d.last_seen||0).getTime()<5*60000,status=onLeave?'On Leave':!recent?'Absent / Offline':d.is_tracking?'Tracking':'Not Tracking';return`<tr><td>${esc(nameOf(p.id))}</td><td>${esc(p.employee_id||'—')}</td><td>${esc(p.role||'Employee')}</td><td><span class="live-dot ${status==='Tracking'?'green':status==='Absent / Offline'?'red':status==='On Leave'?'amber':'gray'}"></span>${status}</td><td>${esc(pById(d?.project_id)?.name||d?.project_name||'No project')}</td><td>${esc(tById(d?.task_id)?.name||d?.task_name||'No task')}</td><td>${esc(d?.device_name||'—')}</td><td>${d?.last_seen?new Date(d.last_seen).toLocaleString():'—'}</td></tr>`}).join('')}</tbody></table></div></div>`}
function drawLeave(){const canReview=roleIsManager();$('#attendanceBody').innerHTML=`<div class="toolbar"><button id="newLeave">+ New Leave Request</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Leave Type</th><th>Start Date</th><th>End Date</th><th>Portion</th><th>Reason</th><th>Status</th><th>Reviewer Comment</th><th>Actions</th></tr></thead><tbody>${state.leaveRequests.map(l=>`<tr><td>${esc(nameOf(l.user_id))}</td><td>${esc(l.leave_type||'')}</td><td>${esc(l.start_date||'')}</td><td>${esc(l.end_date||'')}</td><td>${esc(l.portion||'')}</td><td>${esc(l.reason||'')}</td><td>${esc(l.status||'Pending')}</td><td>${esc(l.reviewer_comment||'')}</td><td>${l.user_id===state.profile.id&&String(l.status).toLowerCase()==='pending'?`<button data-edit-leave="${l.id}">Edit</button>`:''}${canReview&&String(l.status).toLowerCase()==='pending'?` <button class="success" data-approve-leave="${l.id}">Approve</button> <button class="danger" data-reject-leave="${l.id}">Reject</button>`:''}</td></tr>`}).join('')}</tbody></table></div></div>`;$('#newLeave').onclick=()=>leaveModal();$$('[data-edit-leave]').forEach(b=>b.onclick=()=>leaveModal(state.leaveRequests.find(x=>x.id===b.dataset.editLeave)));$$('[data-approve-leave]').forEach(b=>b.onclick=()=>reviewLeave(b.dataset.approveLeave,'Approved'));$$('[data-reject-leave]').forEach(b=>b.onclick=()=>reviewLeave(b.dataset.rejectLeave,'Rejected'))}
function leaveModal(l=null){const ent=num(state.profile.annual_leave_days),used=usedLeave(state.profile.id);modal(l?'Edit Leave Request':'New Leave Request',`<div class="notice">Annual Leave: Entitlement ${fmt(ent)} · Used ${fmt(used)} · Remaining ${fmt(Math.max(0,ent-used))}</div><div class="form-grid"><div class="field"><label>Leave Type</label><select id="lvType">${['Annual Leave','Unpaid Leave','Sick Leave','Other'].map(x=>`<option ${l?.leave_type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Start Date</label><input id="lvStart" type="date" value="${esc(l?.start_date||isoDay())}"></div><div class="field"><label>End Date</label><input id="lvEnd" type="date" value="${esc(l?.end_date||isoDay())}"></div><div class="field"><label>Portion</label><select id="lvPortion">${['Full Day','Morning Half','Afternoon Half'].map(x=>`<option ${l?.portion===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field span3"><label>Reason</label><textarea id="lvReason">${esc(l?.reason||'')}</textarea></div></div>`,async()=>{const row={user_id:state.profile.id,leave_type:$('#lvType').value,start_date:$('#lvStart').value,end_date:$('#lvEnd').value,portion:$('#lvPortion').value,reason:$('#lvReason').value.trim(),status:'Pending'};const r=l?await supabase.from('leave_requests').update(row).eq('id',l.id):await supabase.from('leave_requests').insert(row);if(r.error)return alert(r.error.message);closeModal();await loadAll()})}
function reviewLeave(id,status){modal(`${status} Leave Request`,`<div class="field"><label>Reviewer Comment</label><textarea id="reviewComment"></textarea></div>`,async()=>{const {error}=await supabase.from('leave_requests').update({status,reviewer_comment:$('#reviewComment').value.trim()}).eq('id',id);if(error)return alert(error.message);closeModal();await loadAll()},status)}
function usedLeave(uid){const y=new Date().getFullYear();return state.leaveRequests.filter(l=>l.user_id===uid&&String(l.status).toLowerCase()==='approved'&&String(l.leave_type||'').toLowerCase().includes('annual')&&new Date(l.start_date).getFullYear()===y).reduce((s,l)=>{if(String(l.portion).toLowerCase().includes('half'))return s+.5;let a=new Date(l.start_date),b=new Date(l.end_date),n=0;while(a<=b){if(![0,6].includes(a.getDay()))n++;a.setDate(a.getDate()+1)}return s+Math.max(1,n)},0)}
function drawSchedule(){if(!roleIsManager()){$('#attendanceBody').innerHTML='<div class="notice">Admin/Manager access required.</div>';return}const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];$('#attendanceBody').innerHTML=`<div class="card"><div class="section-title">Weekly Work Schedule</div><div class="table-wrap"><table class="table"><thead><tr><th>Day</th><th>Workday</th><th>Morning</th><th>Afternoon</th><th>OT</th><th>Action</th></tr></thead><tbody>${days.map((d,i)=>{const s=state.shifts.find(x=>num(x.day_of_week)===i);return`<tr><td>${d}</td><td>${s?.is_workday===false?'Off':'Workday'}</td><td>${esc((s?.morning_start||'')+' - '+(s?.morning_end||''))}</td><td>${esc((s?.afternoon_start||'')+' - '+(s?.afternoon_end||''))}</td><td>${esc((s?.ot_start||'')+' - '+(s?.ot_end||''))}</td><td><button data-shift-day="${i}">Edit</button></td></tr>`}).join('')}</tbody></table></div></div><div class="card" style="margin-top:12px"><div class="toolbar"><div class="section-title grow">Holidays / Special Work Days</div><button id="addSpecial">+ Add Day</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Name</th><th>Type</th><th>Morning</th><th>Afternoon</th><th>OT</th><th>Actions</th></tr></thead><tbody>${state.specialDays.map(s=>`<tr><td>${esc(s.work_date)}</td><td>${esc(s.name||'')}</td><td>${s.is_workday?'Special Workday':'Holiday'}</td><td>${esc((s.morning_start||'')+' - '+(s.morning_end||''))}</td><td>${esc((s.afternoon_start||'')+' - '+(s.afternoon_end||''))}</td><td>${esc((s.ot_start||'')+' - '+(s.ot_end||''))}</td><td><button data-edit-special="${s.id}">Edit</button> <button class="danger" data-del-special="${s.id}">Delete</button></td></tr>`}).join('')}</tbody></table></div></div>`;$$('[data-shift-day]').forEach(b=>b.onclick=()=>shiftModal(num(b.dataset.shiftDay)));$('#addSpecial').onclick=()=>specialDayModal();$$('[data-edit-special]').forEach(b=>b.onclick=()=>specialDayModal(state.specialDays.find(x=>x.id===b.dataset.editSpecial)));$$('[data-del-special]').forEach(b=>b.onclick=()=>deleteSpecial(b.dataset.delSpecial))}
function shiftModal(day){const s=state.shifts.find(x=>num(x.day_of_week)===day)||{};modal('Edit Work Schedule',`<div class="form-grid"><div class="field"><label>Workday</label><select id="shWork"><option value="true" ${s.is_workday!==false?'selected':''}>Workday</option><option value="false" ${s.is_workday===false?'selected':''}>Off</option></select></div>${[['Morning Start','morning_start'],['Morning End','morning_end'],['Afternoon Start','afternoon_start'],['Afternoon End','afternoon_end'],['OT Start','ot_start'],['OT End','ot_end']].map(([l,k])=>`<div class="field"><label>${l}</label><input id="${k}" type="time" value="${esc(s[k]||'')}"></div>`).join('')}</div>`,async()=>{const row={day_of_week:day,is_workday:$('#shWork').value==='true',morning_start:$('#morning_start').value||null,morning_end:$('#morning_end').value||null,afternoon_start:$('#afternoon_start').value||null,afternoon_end:$('#afternoon_end').value||null,ot_start:$('#ot_start').value||null,ot_end:$('#ot_end').value||null};const {error}=await supabase.from('work_shift_settings').upsert(row,{onConflict:'day_of_week'});if(error)return alert(error.message);closeModal();await loadAll()})}
function specialDayModal(s=null){modal(s?'Edit Special Day':'Add Special Day',`<div class="form-grid"><div class="field"><label>Date</label><input id="sdDate" type="date" value="${esc(s?.work_date||isoDay())}"></div><div class="field"><label>Name</label><input id="sdName" value="${esc(s?.name||'')}"></div><div class="field"><label>Type</label><select id="sdWork"><option value="false" ${s?.is_workday?'':'selected'}>Holiday</option><option value="true" ${s?.is_workday?'selected':''}>Special Workday</option></select></div></div>`,async()=>{const row={work_date:$('#sdDate').value,name:$('#sdName').value.trim(),is_workday:$('#sdWork').value==='true'};const r=s?await supabase.from('special_work_days').update(row).eq('id',s.id):await supabase.from('special_work_days').upsert(row,{onConflict:'work_date'});if(r.error)return alert(r.error.message);closeModal();await loadAll()})} async function deleteSpecial(id){if(!confirm('Delete this day?'))return;const {error}=await supabase.from('special_work_days').delete().eq('id',id);if(error)alert(error.message);else loadAll()}
function drawBalances(){if(!roleIsManager()){$('#attendanceBody').innerHTML='<div class="notice">Admin/Manager access required.</div>';return}$('#attendanceBody').innerHTML=`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Employee ID</th><th>Annual Entitlement</th><th>Used</th><th>Remaining</th><th>Action</th></tr></thead><tbody>${state.profiles.filter(p=>p.active!==false).map(p=>{const e=num(p.annual_leave_days),u=usedLeave(p.id);return`<tr><td>${esc(nameOf(p.id))}</td><td>${esc(p.employee_id||'—')}</td><td>${fmt(e)}</td><td>${fmt(u)}</td><td>${fmt(Math.max(0,e-u))}</td><td><button data-leave-bal="${p.id}">Edit</button></td></tr>`}).join('')}</tbody></table></div></div>`;$$('[data-leave-bal]').forEach(b=>b.onclick=()=>leaveBalanceModal(b.dataset.leaveBal))}
function leaveBalanceModal(uid){const p=prof(uid);modal('Annual Leave Entitlement',`<div class="field"><label>${esc(nameOf(uid))}</label><input id="leaveEnt" type="number" min="0" step="0.5" value="${num(p?.annual_leave_days)}"></div>`,async()=>{const {error}=await supabase.from('profiles').update({annual_leave_days:num($('#leaveEnt').value)}).eq('id',uid);if(error)return alert(error.message);closeModal();await loadAll()})}

function renderMonitor(){if(!roleIsManager()){$('#page-monitor').innerHTML='<div class="notice">Admin/Manager access required.</div>';return}const people=state.profiles.filter(p=>p.active!==false);$('#page-monitor').innerHTML=`<div class="toolbar"><div class="field"><label>Employee</label><select id="monEmp">${people.map(p=>`<option value="${p.id}">${esc(nameOf(p.id))} (${esc(p.employee_id||'')}) · ${esc(p.role||'Employee')}</option>`).join('')}</select></div><div class="field"><label>Date</label><input id="monDate" type="date" value="${isoDay()}"></div><button id="monLoad" class="primary">Reload</button></div><div id="monInfo" class="muted small"></div><div id="monShots" class="screenshot-grid" style="margin-top:12px"></div>`;$('#monLoad').onclick=loadMonitor;$('#monEmp').onchange=loadMonitor;$('#monDate').onchange=loadMonitor;loadMonitor()}
async function loadMonitor(){const uid=$('#monEmp').value,day=$('#monDate').value,shots=state.screenshots.filter(s=>s.user_id===uid&&String(s.captured_at||'').slice(0,10)===day).sort((a,b)=>new Date(b.captured_at)-new Date(a.captured_at));$('#monInfo').textContent=`${nameOf(uid)}: ${shots.length} screenshots on ${day}.`;await drawShotCards(shots,$('#monShots'))}

function renderEmployees(){if(!roleIsAdmin()){$('#page-employees').innerHTML='<div class="notice">Admin access required.</div>';return}const rows=state.profiles;$('#page-employees').innerHTML=`<div class="toolbar"><button id="newEmployee">+ New Employee</button><div class="field grow"><label>Search</label><input id="empSearch" placeholder="Search employee..."></div></div><div class="grid" style="grid-template-columns:repeat(4,1fr);margin-bottom:12px">${[['Employees',rows.length],['Active',rows.filter(x=>x.active!==false).length],['Admins',rows.filter(x=>x.role==='Admin').length],['Managers',rows.filter(x=>x.role==='Manager').length]].map(([l,v])=>`<div class="kpi"><div class="label">${l}</div><div class="value">${v}</div></div>`).join('')}</div><div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Employee ID</th><th>Email</th><th>Role</th><th>Annual Leave</th><th>Used</th><th>Remaining</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(p=>{const e=num(p.annual_leave_days),u=usedLeave(p.id);return`<tr data-emp-row data-search="${esc([p.display_name,p.employee_id,p.email,p.role].join(' ').toLowerCase())}"><td>${esc(nameOf(p.id))}</td><td>${esc(p.employee_id||'—')}</td><td>${esc(p.email||'—')}</td><td>${esc(p.role||'Employee')}</td><td>${fmt(e)}</td><td>${fmt(u)}</td><td>${fmt(Math.max(0,e-u))}</td><td>${p.active===false?'Inactive':'Active'}</td><td><button data-edit-emp="${p.id}">Edit</button> <button class="${p.active===false?'success':'danger'}" data-toggle-emp="${p.id}">${p.active===false?'Activate':'Deactivate'}</button></td></tr>`}).join('')}</tbody></table></div>`;$('#newEmployee').onclick=()=>employeeModal();$('#empSearch').oninput=e=>{const q=e.target.value.toLowerCase();$$('[data-emp-row]').forEach(r=>r.classList.toggle('hidden',q&&!r.dataset.search.includes(q)))};$$('[data-edit-emp]').forEach(b=>b.onclick=()=>employeeModal(prof(b.dataset.editEmp)));$$('[data-toggle-emp]').forEach(b=>b.onclick=()=>toggleEmployee(b.dataset.toggleEmp))}
async function createAuthEmployee(email,password,metadata){const temp=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await temp.auth.signUp({email,password,options:{data:metadata}});try{await temp.auth.signOut()}catch{}if(error)throw error;return data.user}
function employeeModal(p=null){modal(p?'Edit Employee':'New Employee',`<div class="form-grid"><div class="field"><label>Display Name</label><input id="eName" value="${esc(p?.display_name||'')}"></div><div class="field"><label>Employee ID</label><input id="eId" value="${esc(p?.employee_id||'')}"></div><div class="field"><label>Email</label><input id="eEmail" type="email" value="${esc(p?.email||'')}" ${p?'readonly':''}></div><div class="field"><label>Role</label><select id="eRole">${['Employee','Manager','Admin'].map(r=>`<option ${p?.role===r?'selected':''}>${r}</option>`).join('')}</select></div><div class="field"><label>Annual Leave Days</label><input id="eLeave" type="number" step="0.5" min="0" value="${num(p?.annual_leave_days)}"></div>${p?'':`<div class="field"><label>Temporary Password</label><input id="ePass" type="password"></div>`}</div>`,async()=>{let uid=p?.id;const row={display_name:$('#eName').value.trim(),employee_id:$('#eId').value.trim(),email:$('#eEmail').value.trim().toLowerCase(),role:$('#eRole').value,annual_leave_days:num($('#eLeave').value),active:p?.active!==false};if(!p){try{const u=await createAuthEmployee(row.email,$('#ePass').value,{display_name:row.display_name,employee_id:row.employee_id});uid=u?.id}catch(e){return alert(e.message)}}for(let i=0;i<8&&!p;i++){const {data}=await supabase.from('profiles').select('id').eq('id',uid).maybeSingle();if(data)break;await new Promise(r=>setTimeout(r,250))}const {error}=await supabase.from('profiles').update(row).eq('id',uid);if(error)return alert(error.message);closeModal();await loadAll()})}
async function toggleEmployee(uid){const p=prof(uid),next=p?.active===false;if(uid===state.profile.id&&!next)return alert('You cannot deactivate yourself.');const {error}=await supabase.from('profiles').update({active:next}).eq('id',uid);if(error)alert(error.message);else loadAll()}

function renderSettings(){$('#page-settings').innerHTML=`<div class="card" style="max-width:900px"><div class="section-title">Web Portal Settings</div><div class="notice">Tracking capture settings remain in the Windows desktop agent because a browser cannot monitor global keyboard/mouse activity, detect all desktop applications, or capture the entire desktop in the background.</div><div class="form-grid"><div class="field"><label>Supabase</label><input readonly value="Connected"></div><div class="field"><label>Portal</label><input readonly value="DDG Tracking Web"></div><div class="field"><label>Signed screenshot URL lifetime</label><input readonly value="10 minutes"></div></div></div>`}
function renderAbout(){$('#page-about').innerHTML=`<div class="card" style="max-width:900px"><div class="section-title">DDG Tracking Web</div><p>Web management portal synchronized with the DDG Tracking Windows desktop agent through Supabase.</p><p><b>Web:</b> Dashboard, Projects, Tasks, Change Orders, Production, Screenshots, Attendance, Team Monitor and Employee Management.</p><p><b>Desktop agent:</b> Start/Stop tracking, keyboard/mouse activity, active applications, automatic screenshots, offline/background tracking and system tray operation.</p><p class="muted">Version Web 4.0</p></div>`}

supabase.auth.getSession().then(async({data})=>{if(data.session?.user)showMain(data.session.user)});
